[package]
name = "rsnow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "2.0.1"
rand = "0.8.5"
libc = "0.2.149"
signal-hook = "0.3.10"
